<a href="https://colab.research.google.com/github/kimdanni/python/blob/circleci-project-setup/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Numpy import 하기

In [9]:
import numpy

In [10]:
numpy

<module 'numpy' from '/usr/local/lib/python3.6/dist-packages/numpy/__init__.py'>

### 1-1. 별칭 (alias) 지정하기 (항상 해주세요!)

In [11]:
import numpy as np

In [12]:
np

<module 'numpy' from '/usr/local/lib/python3.6/dist-packages/numpy/__init__.py'>

### 1-2 ndarray (n dimension array)

In [14]:
arr = np.array([1,2,3,4], dtype = int)


In [15]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [16]:
[1, 2, 3, 4]

[1, 2, 3, 4]

In [17]:
type(arr)

numpy.ndarray

### 2-1. list로 부터 생성하기

In [18]:
mylist1 = [1, 2, 3, 4]

In [19]:
mylist2 = [[1, 2, 3, 4], 
           [5, 6, 7, 8]]

In [20]:
arr1 = np.array(mylist1)


In [21]:
arr2 = np.array(mylist2)


### 2-2. shape확인하기
#### shape은 **차원의 수**를 확인 (axis와 shape에 대해 정확한 이해 필요)
#### axis : 축 (axis 0 = 행, axis 1 = 열)

In [22]:
arr1.shape


(4,)

In [23]:
arr2.shape


(2, 4)

## 3. array에서의 data 타입

array에서는 list와는 다르게 1개의 **단일 데이터 타입**만 허용 됩니다.

### 3-1. list에서의 data 타입

In [24]:
mylist = [1, 3.14, '테디', '1234']

In [25]:
mylist

[1, 3.14, '테디', '1234']

In [26]:
mylist[1]


3.14

In [27]:
mylist[2]

'테디'

### 3-2. array에서의 data 타입 (case를 통한 연구)

### case 1. int와 float 타입이 혼재된 경우

In [28]:
arr = np.array([1, 2, 3, 3.14])

In [29]:
arr

array([1.  , 2.  , 3.  , 3.14])

### case 2. int와 float 타입이 혼재되었으나, dtype을 지정한 경우

In [35]:
arr = np.array([1, 2, 3, 3.14], dtype = int)

In [36]:
arr

array([1, 2, 3, 3])

### case 3. int와 str 타입이 혼재된 경우

In [38]:
arr = np.array([1, 3.14, '테디', '1234'])

In [39]:
arr

array(['1', '3.14', '테디', '1234'], dtype='<U32')

In [40]:
arr[0] + arr[1]

'13.14'

### case 4. int와 str 타입이 혼재되어 있고 int로 dtype을 지정한 경우

In [41]:
arr = np.array([1, 3.14, '1234'], dtype=int)

In [42]:
arr

array([   1,    3, 1234])