<a href="https://colab.research.google.com/github/kimdanni/python/blob/circleci-project-setup/numpy5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

## 1. 행렬 - 덧셈

### 1-1. 덧셈

##### shape이 같아야 한다.
##### 같은 position끼리 연산해야 한다.

In [14]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [15]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [16]:
a + b


array([[4, 6, 8],
       [3, 5, 7]])

In [17]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [18]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [19]:
a + b

ValueError: ignored

### 1-2. Sum

In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [20]:
np.sum(a, axis = 0)


array([3, 5, 7])

In [21]:
np.sum(a, axis = 1)


array([6, 9])

## 2. 행렬 - 뺄셈

In [24]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [25]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [26]:
a - b

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [27]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [28]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [29]:
a - b

ValueError: ignored

## 3. 곱셈

일반 곱셈

In [30]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [31]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [32]:
a.shape, b.shape

((2, 3), (2, 3))

In [33]:
a * b


array([[ 3,  8, 15],
       [ 2,  6, 12]])

단순 곱셈과 dot product는 다릅니다. 이점 유의하세요!

In [34]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [35]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [36]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [37]:
a * b

ValueError: ignored

In [40]:
a = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])

In [41]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [42]:
a.shape, b.shape #맞닿은 부분이 같아야 한다, 결과는 밖에 있는 애들

((3, 3), (3, 2))

In [45]:
np.dot(a,b)


array([[22, 28],
       [22, 28],
       [31, 40]])

In [46]:
a.dot(b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [47]:
1*1 + 2*3 + 3*5

22

In [48]:
1*2 + 2*4 + 3*6

28